version: 2
jobs:
  build-and-test-server:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run: 
          working_directory: /home/circleci/project/server
          command: npm install 
      - run: 
          working_directory: /home/circleci/project/server
          command: npm run lint
  build-and-test-client:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run: 
          working_directory: /home/circleci/project/client
          command: npm install 
      - run: 
          working_directory: /home/circleci/project/client
          command: npm run lint
  
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test-server
        - build-and-test-client