version: 2
jobs:
  build-and-test-server:
    docker:
      - image: circleci/node:12.16.0
    working_directory: /home/circleci/project/server
    steps:
      - checkout
      - run: pwd
      - run: npm install 
      - run: pwd
      - run: npm run lint
      - run: pwd
  build-and-test-client:
    docker:
      - image: circleci/node:12.16.0
    working_directory: /home/circleci/project/client
    steps:
      - checkout
      - run: npm install 
      - run: npm run lint
  
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test-server
        - build-and-test-client 