version: 2

orbs:
  heroku: circleci/heroku@0.0.10. # Invoke the Heroku orb

jobs:
  build-and-test-server:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run: 
          working_directory: /home/circleci/project/server
          command: npm install 
      - run: 
          working_directory: /home/circleci/project/server
          command: npm run lint
  build-and-test-client:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run: 
          working_directory: /home/circleci/project/client
          command: npm install 
      - run: 
          working_directory: /home/circleci/project/client
          command: npm run lint
  deploy-client:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run: 
          working_directory: /home/circleci/project/client
          command: npm install 
      - run: 
          working_directory: /home/circleci/project/client
          command: npm run build
      - run:
          working_directory: /home/circleci/project/client
          command: npm run deploy
  deloy-server:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - run:
          name: Setup Heroku
          working_directory: /home/circleci/project
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          working_directory: /home/circleci/project
          command: |
            git push heroku master

workflows:
    version: 2
    build-and-test:
      jobs:
        - heroku/deploy-via-git
