version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd server
            - run: npm install
            - run: cd ..
  deployment:
    steps:
      - checkout
      - run: npm install surge
      - run: surge --project ./ --domain queueoverflow.surge.sh

workflows:
    build-and-test:
      jobs:
        - build-and-test