version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd server
            - run: npm install
            - run: npm install eslint -g
            - run: npm run eslint
            - run: echo pwd
            - run: cd ..
            - run: cd client
            - run: npm install
            - run: npm run eslint
            - run: cd ..
workflows:
    build-and-test:
      jobs:
        - build-and-test 